# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XL4Uozg_LSlHT8v7MOOrKg1r_2Gb085H
"""

import streamlit as st
import pandas as pd
from sklearn import linear_model

df = pd.read_csv('pizzas.csv')

modelo = linear_model.LinearRegression()

x = df[['diametro']]
y = df[['preco']]

modelo.fit(x, y)


st.title('Prevendo o valor de uma pizza')
st.divider()

diametro = st.number_input('Digite o tamanho do diâmetro da pizza: ')

if diametro:
    preco_previsto = modelo.predict([[diametro]])[0][0]
    st.write(f'O valor da pizza com diâmetro de {diametro:.2f} cm é de R${preco_previsto:.2f}.')